import request from '@/utils/request'
import type { Admin, ApiResponse, DrawRecord, LotteryType, PageData, Permission, Role, SystemConfig } from '@/types'
export const login=(data:{username:string;password:string})=>request.post<any,ApiResponse<{token:string;admin:Admin}>>('/admin/login',data)
export const current=()=>request.get<any,ApiResponse<Admin>>('/admin/current')
export const changePassword=(data:{current_password:string;new_password:string;confirm_password:string})=>request.post('/admin/password',data)
export const getAdmins=()=>request.get<any,ApiResponse<Admin[]>>('/admin/admins')
export const createAdmin=(data:unknown)=>request.post('/admin/admins',data)
export const updateAdmin=(id:number,data:unknown)=>request.put(`/admin/admins/${id}`,data)
export const deleteAdmin=(id:number)=>request.delete(`/admin/admins/${id}`)
export const getRoles=()=>request.get<any,ApiResponse<Role[]>>('/admin/roles')
export const createRole=(data:unknown)=>request.post('/admin/roles',data)
export const updateRole=(id:number,data:unknown)=>request.put(`/admin/roles/${id}`,data)
export const deleteRole=(id:number)=>request.delete(`/admin/roles/${id}`)
export const getPermissions=()=>request.get<any,ApiResponse<Permission[]>>('/admin/permissions')
export const getLotteryTypes=()=>request.get<any,ApiResponse<LotteryType[]>>('/admin/lottery-types')
export const createLotteryType=(data:Omit<LotteryType,'id'|'created_at'|'updated_at'>)=>request.post('/admin/lottery-types',data)
export const updateLotteryType=(id:number,data:Omit<LotteryType,'id'|'created_at'|'updated_at'>)=>request.put(`/admin/lottery-types/${id}`,data)
export const deleteLotteryType=(id:number)=>request.delete(`/admin/lottery-types/${id}`)
export const getDrawRecords=(params:{page:number;page_size:number;lottery_type_id?:number;issue_number?:string})=>request.get<any,ApiResponse<PageData<DrawRecord>>>('/admin/draw-records',{params})
export const getSystemConfig=()=>request.get<any,ApiResponse<SystemConfig>>('/admin/system-config')
export const updateSafeWBot=(data:{token:string;chat_ids:string[]})=>request.put('/admin/system-config/safew-bot',data)
